### ISSUE TITLE
Write 'Shrub' to LC_Class field in sheet

### ISSUE THREAD

**Issue by ktarrio** [parevalo/tstools_online#25]
Currently (version as of 4/20) 'Shrubs' do not write to the sheet -- when 'Shrubs' are selected as a class in the tool, they are written as 'Unfilled'

**NOTE**: Konrad has identified and fixed this issue for the version of the tool circa February--the version that the students are working with--but these changes are not in the 4/20 version

**Comment by parevalo** [comment]
Thank you Konrad!
